version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - '8888:5432'
    networks:
      - backend

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5007:5000
    networks:
      - backend
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    depends_on:
      - db
    restart: always

networks:
  backend:
